### ISSUE TITLE
File I/O issue

### ISSUE THREAD

**Issue by r00tr4v3n** [taneryilmaz/libconfigini#1]
Hello,
It might be usefull to implement the creation of a config file in ConfigReadFile if it does not exist.

**Comment by taneryilmaz** [comment]
Hi r00tr4v3n,

In "ConfigRet ConfigRead(FILE _fp, Config *_cfg)" method:

If you have created a Config instance and passed its address it must be in exact state

```
if ( !fp || !cfg || (*cfg && ((*cfg)->initnum != CONFIG_INIT_MAGIC)) )
    return CONFIG_ERR_INVALID_PARAM;
```

If you did not create an instance and want to be created in ConfigRead method your address pointer must point to NULL. So a new config handler is created and assigned to your address pointer securely.

```
if (*cfg == NULL) {
    _cfg = ConfigNew();
    if (_cfg == NULL)
        return CONFIG_ERR_MEMALLOC;
    *cfg = _cfg;
    newcfg = true;
}
else
    _cfg = *cfg;
```

For this pupose, the code blocks seems like that:

```
Config *cfg = NULL;
ConfigRead(fp, &cfg);
```

Regards,
Taner

**Comment by taneryilmaz** [comment]
Hello,
If you print error string in your codes it will be more informative. For this, please add those headers and change above your code like that:

#include <errno.h>#include <string.h>
...
if (ConfigReadFile( PATH, &cfg) != CONFIG_OK) {
    LOG_ERR("ConfigOpenFile failed for %s: %s", PATH, strerror(errno));
    return;
}
Regards,Taner 


     On Tuesday, June 9, 2015 8:39 PM, r00tr4v3n <notifications@github.com> wrote:
   

 Hello,
I cannot open (write) a config file outside the users home directory under Linux. The folders exist and owned by the same user. Any ideas? if (ConfigReadFile( PATH, &cfg) != CONFIG_OK) {
    LOG_ERR("ConfigOpenFile failed for %s", PATH);
    return;
}

ConfigOpenFile failed for /home/user/workspace/config.conf
