### ISSUE TITLE
Memory leak in ConfigNew() / ConfigFree()

### ISSUE THREAD

**Issue by hugovangalen** [taneryilmaz/libconfigini#2]
In ConfigFree(), the allocated pointers by the strdup() calls in the ConfigNew() are not cleaned up..

These lines need to be added to ConfigFree(), right before the free(cfg) call to prevent memory slowly leaking away:

```
if (cfg->comment_chars) free(cfg->comment_chars);
if (cfg->true_str) free(cfg->true_str);
if (cfg->false_str) free(cfg->false_str);
```

**Comment by taneryilmaz** [comment]
Thank you Hugo van Galen (hugovangalen). The bug is fixed.
Regards.
